VidlyMoshNet8/Controllers/API/MoviesController.cs
using System.Net;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VidlyMoshNet8.Data;
using VidlyMoshNet8.DTO;
using VidlyMoshNet8.Models;

namespace VidlyMoshNet8.Controllers.API
{
    [Route("api/movies")]
    [ApiController]
    public class MoviesController : Controller
    {
        private AppDbContext _context;
        private readonly IMapper _mapper;

        public MoviesController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult GetMovies()
        {
            return Ok(_context.Movies
                .Include(m => m.Genre)
                .Where(m => m.NumberAvailable > 0) 
				.ToList()
                .Select(_mapper.Map<Movie, MovieDTO>));
        }

        [HttpGet("{id}")]
        public IActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movie == null)
            {
                throw new HttpRequestException(HttpStatusCode.BadRequest.ToString());
            }
            return Ok(_mapper.Map<Movie, MovieDTO>(movie));
        }

        [HttpPost]
        public IActionResult CreateMovie(MovieDTO movieDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var movie = _mapper.Map<MovieDTO, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();

            movieDto.Id = movie.Id;
            return Created(Request.Path.ToString() + "/" + movie.Id, movieDto);
        }

        [HttpPut("{id}")]
        public IActionResult UpdateMovie(int id, MovieDTO movieDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movieInDb == null)
            {
                throw new HttpRequestException(HttpStatusCode.BadRequest.ToString());
            }
            _mapper.Map(movieDto, movieInDb);
            _context.SaveChanges();
            return Ok();
        }

        [HttpDelete("{id}")]
        public IActionResult DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movieInDb == null)
            {
                throw new HttpRequestException(HttpStatusCode.BadRequest.ToString());
            }
            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();
            return Ok();
        }
    }
}

VidlyMoshNet8/Controllers/RentalController.cs
using Microsoft.AspNetCore.Mvc;

namespace VidlyMoshNet8.Controllers
{
    public class RentalController : Controller
    {
        public ActionResult New()
        {
            return View();
        }
    }
}

VidlyMoshNet8/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VidlyMoshNet8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/lumen-bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="css/typeahead.css"/>
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VidlyMoshNet8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    @if (signInManager.IsSignedIn(User))
                    {
                        
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rental" asp-action="New">Rentals</a>

                            </li>
                    }
                    </ul>
                    

                    <ul class="navbar-nav flex-grow-2">
                        
                        @if(signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                @User?.Identity?.Name
                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout </a>
                            </li> 
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register </a>
                            </li>
                            <li class="nav-item">
                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - VidlyMoshNet8 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootbox/bootbox.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/typeahead.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>